server:
  port: 8080
spring:
  application:
    name: invitaciones
  mongodb:
    uri: mongodb+srv://abgTani0315:cY5_zR2S_bYZNj7@clusterboda.jk4h3yp.mongodb.net/invitaciones?retryWrites=true&w=majority
app:
  jwt:
    secret: "TANIA_ABDIEL_2026_CAMBIAR_EN_PROD_MIN_256_BITS"



